V20
appgate/terraform-provider-appgatesdp pull request #357
Opened 2024-03-27 13:25 UTC by kajes

2024-03-27 13:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/appgate/terraform-provider-appgatesdp?pullRequest=357) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/appgate/terraform-provider-appgatesdp?pullRequest=357) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/appgate/terraform-provider-appgatesdp?pullRequest=357) it.</sub>

2024-03-28 21:50 UTC, mandopaloooza commented on appgate/resource_appgate_appliance.go
> +									},
Running this in 6.1 and 6.2 yields this error. We support 2 versions back so most likely missing a version checker in the code that touches this resource
```
=== NAME  TestAccAppliance62MetricsAggregator
    resource_appgate_appliance_test.go:4707: Step 1/2 error: Error running pre-apply refresh: exit status 1

        Error: metrics_aggregator.0.prometheus_exporter.0.labels_disabled: unknown element type (internal)

          with appgatesdp_appliance.appliancev62_metrics_aggregator,
          on terraform_plugin_test.tf line 6, in resource "appgatesdp_appliance" "appliancev62_metrics_aggregator":
           6: resource "appgatesdp_appliance" "appliancev62_metrics_aggregator" {
```

2024-03-28 21:50 UTC, mandopaloooza commented on appgate/resource_appgate_site.go
> +									},
Need to increment the number of elements in test
```
=== RUN   TestAccSiteBasicAwsResolverWithoutSecret
    resource_appgate_site_test.go:615: Step 1/2 error: Check failed: Check 13/39 error: appgatesdp_site.test_site: Attribute 'name_resolution.0.aws_resolvers.0.%' expected "11", got "12"
```

2024-04-17 12:42 UTC, kajes commented
Test are working now, so proper code review in place

2024-04-17 14:31 UTC, mandopaloooza requested changes
Looks good overall + Test passes on 6.1 - 6.3

I know it is tedious work but markdown files (documentation) needs updating for some of the new/old fields. From a quick scan with my eyes, I think we are missing the following fields:
- `prometheus_exporter.labels_disabled`
-  `azure_monitor.scope`
-  fields for datadog and corelogix

2024-04-23 16:55 UTC, mandopaloooza approved these changes

2024-04-25 06:25 UTC, merged